extends Control

@onready var dashboard: Control = $Dashboard
@onready var create_classcode: Control = $CreateClasscode
@onready var students: Control = $Students
@onready var leaderboard: Control = $Leaderboard
@onready var back_button: TextureButton = $BackButton

@onready var create_class_code_button: Button = $Dashboard/Control3/Panel/CreateClassCodeButton
@onready var student_button: Button = $Dashboard/Control3/Panel/StudentButton
@onready var leaderboard_button: Button = $Dashboard/Control3/Panel/LeaderboardButton

@onready var class_code_edit: LineEdit = $CreateClasscode/CodeGeneratorPanel/ClassCodeEdit
@onready var copy_code_button: Button = $CreateClasscode/CodeGeneratorPanel/CopyCodeButton
@onready var generate_new_code_button: Button = $CreateClasscode/CodeGeneratorPanel/GenerateNewCodeButton

@onready var profile_name_label: Label = $TeacherProfilePanel/Label
@onready var greeting_name_label: Label = $Dashboard/GreetingPanel/GreetingLabel2
@onready var grade_label: Label = $CreateClasscode/Panel/GradeLabel
@onready var teacher_label: Label = $CreateClasscode/Panel/TeacherLabel

# --- Leaderboard (populated live from Supabase) ---
@onready var podium_slots := [$Leaderboard/First, $Leaderboard/Second, $Leaderboard/Third]
@onready var empty_roster_message: Label = $Leaderboard/EmptyRosterMessage
@onready var levels_graph_panel: Panel = $Leaderboard/LevelsGraphPanel
@onready var empty_graph_message: Label = $Leaderboard/LevelsGraphPanel/EmptyGraphMessage

const MAX_EXTRA_ROWS := 5
const MAX_GRAPH_BARS := 6
var _dynamic_leaderboard_nodes: Array = []
var _bold_font: FontFile = load("res://Nunito-Bold.ttf")

func _ready() -> void:
	_load_teacher_info()
	_show_dashboard()
	_connect_signals()
	# The class code is permanent once generated - there's nothing to regenerate.
	if generate_new_code_button:
		generate_new_code_button.hide()

func _load_teacher_info() -> void:
	var gm = get_node_or_null("/root/GameManager")
	if not gm:
		return

	var display_name: String = gm.get("player_name") if "player_name" in gm else ""
	if display_name != "":
		if profile_name_label: profile_name_label.text = display_name
		if greeting_name_label: greeting_name_label.text = display_name + "!"
		if teacher_label: teacher_label.text = "Teacher: " + display_name

	var grade_subject: String = gm.get("grade_subject") if "grade_subject" in gm else ""
	if grade_subject != "" and grade_label:
		grade_label.text = grade_subject

	if class_code_edit and gm.has_method("get_or_create_class_code"):
		class_code_edit.text = gm.get_or_create_class_code()

func _connect_signals() -> void:
	if create_class_code_button and not create_class_code_button.pressed.is_connected(_on_create_class_code_pressed):
		create_class_code_button.pressed.connect(_on_create_class_code_pressed)
	if student_button and not student_button.pressed.is_connected(_on_student_button_pressed):
		student_button.pressed.connect(_on_student_button_pressed)
	if leaderboard_button and not leaderboard_button.pressed.is_connected(_on_leaderboard_button_pressed):
		leaderboard_button.pressed.connect(_on_leaderboard_button_pressed)
	if back_button and not back_button.pressed.is_connected(_on_back_pressed):
		back_button.pressed.connect(_on_back_pressed)
	if copy_code_button and not copy_code_button.pressed.is_connected(_on_copy_code_pressed):
		copy_code_button.pressed.connect(_on_copy_code_pressed)

func _hide_all_pages() -> void:
	if dashboard: dashboard.hide()
	if create_classcode: create_classcode.hide()
	if students: students.hide()
	if leaderboard: leaderboard.hide()

func _show_dashboard() -> void:
	_hide_all_pages()
	if dashboard: dashboard.show()
	if back_button: back_button.hide()

func _on_create_class_code_pressed() -> void:
	_hide_all_pages()
	if create_classcode: create_classcode.show()
	if back_button: back_button.show()

func _on_student_button_pressed() -> void:
	_hide_all_pages()
	if students: students.show()
	if back_button: back_button.show()

func _on_leaderboard_button_pressed() -> void:
	_hide_all_pages()
	if leaderboard: leaderboard.show()
	if back_button: back_button.show()
	_refresh_leaderboard()

func _on_back_pressed() -> void:
	_show_dashboard()

func _on_copy_code_pressed() -> void:
	if class_code_edit:
		DisplayServer.clipboard_set(class_code_edit.text)

# --- LEADERBOARD (live data from Supabase, offline-safe) ---

func _refresh_leaderboard() -> void:
	var gm = get_node_or_null("/root/GameManager")
	var sync = get_node_or_null("/root/SyncManager")
	if not gm or not sync or gm.class_code == "":
		_render_leaderboard([])
		return
	sync.fetch_leaderboard(gm.class_code, _render_leaderboard)

func _render_leaderboard(students_data: Array) -> void:
	# Clear anything generated by a previous refresh before rebuilding.
	for node in _dynamic_leaderboard_nodes:
		if is_instance_valid(node):
			node.queue_free()
	_dynamic_leaderboard_nodes.clear()

	_render_podium(students_data)
	_render_extra_rows(students_data)
	_render_graph(students_data)

func _render_podium(students_data: Array) -> void:
	for i in range(podium_slots.size()):
		var slot: Panel = podium_slots[i]
		var name_label: Label = slot.get_node_or_null("Panel/Label")
		var score_label: Label = slot.get_node_or_null("Panel/Label2")
		if i < students_data.size():
			var row: Dictionary = students_data[i]
			if name_label: name_label.text = str(row.get("player_name", "Student"))
			if score_label: score_label.text = "Lvl " + str(row.get("unlocked_level", 1))
		else:
			if name_label: name_label.text = "—"
			if score_label: score_label.text = "—"

func _render_extra_rows(students_data: Array) -> void:
	if not empty_roster_message:
		return

	if students_data.size() <= 3:
		empty_roster_message.visible = students_data.is_empty()
		return

	empty_roster_message.hide()
	var extra: Array = students_data.slice(3, 3 + MAX_EXTRA_ROWS)
	var row_top := 774.0
	var row_height := 44.0
	for i in range(extra.size()):
		var row: Dictionary = extra[i]
		var label := Label.new()
		label.text = "     %d           %s          Lvl %s" % [i + 4, str(row.get("player_name", "Student")), str(row.get("unlocked_level", 1))]
		label.add_theme_font_override("font", _bold_font)
		label.add_theme_font_size_override("font_size", 24)
		label.add_theme_color_override("font_color", Color(0.096, 0.096, 0.096, 1))
		label.position = Vector2(90, row_top + i * row_height)
		label.size = Vector2(578, row_height)
		leaderboard.add_child(label)
		_dynamic_leaderboard_nodes.append(label)

func _render_graph(students_data: Array) -> void:
	if not levels_graph_panel:
		return

	if students_data.is_empty():
		if empty_graph_message: empty_graph_message.show()
		return
	if empty_graph_message: empty_graph_message.hide()

	var bar_students: Array = students_data.slice(0, min(MAX_GRAPH_BARS, students_data.size()))
	var max_level := 1
	for row in bar_students:
		max_level = max(max_level, int(row.get("unlocked_level", 1)))

	var top := 90.0
	var row_height := 55.0
	var bar_max_width := 360.0
	for i in range(bar_students.size()):
		var row: Dictionary = bar_students[i]
		var level_value: int = int(row.get("unlocked_level", 1))
		var y := top + i * row_height
		var bar_width: float = max(6.0, (float(level_value) / float(max_level)) * bar_max_width)

		var name_label := Label.new()
		name_label.text = str(row.get("player_name", "Student"))
		name_label.add_theme_font_override("font", _bold_font)
		name_label.add_theme_font_size_override("font_size", 20)
		name_label.position = Vector2(30, y)
		name_label.size = Vector2(110, 28)
		levels_graph_panel.add_child(name_label)
		_dynamic_leaderboard_nodes.append(name_label)

		var fill := ColorRect.new()
		fill.color = Color(0.9137255, 0.6, 0.15, 1)
		fill.position = Vector2(150, y + 2)
		fill.size = Vector2(bar_width, 24)
		levels_graph_panel.add_child(fill)
		_dynamic_leaderboard_nodes.append(fill)

		var value_label := Label.new()
		value_label.text = str(level_value)
		value_label.add_theme_font_override("font", _bold_font)
		value_label.add_theme_font_size_override("font_size", 20)
		value_label.position = Vector2(150 + bar_width + 8, y)
		value_label.size = Vector2(52, 28)
		levels_graph_panel.add_child(value_label)
		_dynamic_leaderboard_nodes.append(value_label)
